# Generated by Django 4.2.2 on 2023-06-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogboard', '0002_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Travels', max_length=255),
        ),
    ]
