# Generated by Django 4.2.2 on 2023-06-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogboard', '0009_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='click link ', max_length=255),
        ),
    ]
