# Generated by Django 4.2.2 on 2023-06-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogboard', '0014_profile_facebook_url_profile_insta_profile_pinterest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='insta',
            new_name='instagram_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='pinterest',
            new_name='pinterest_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
